const { Router } = require('express');
const TeamController = require('../controllers/team.controller');
const router = Router();
router.get('/', TeamController.getAll);
router.get('/:id', TeamController.getById);
router.post('/', TeamController.create);
router.put('/:id', TeamController.update);
router.delete('/:id', TeamController.delete);
router.post('/:id/users', TeamController.assignUsers);
router.get('/:id/users', TeamController.allUsers);
router.delete('/:id/users/:user_id', TeamController.removeUser);
module.exports = router;